---
url: "https://raw.githubusercontent.com/deepaksharma208/swagger/master/dist/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"


