apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: swagger-ui-vanoord-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    #nginx.ingress.kubernetes.io/proxy-body-size: "10M"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    {{ if  .Values.prod }}- host: {{.Release.Namespace}}.{{.Values.ingress.proddomain}}
    {{- else }}- host: {{.Release.Namespace}}.{{.Values.ingress.devdomain}}
    {{- end }}
      http:
        paths:
        - backend:
            serviceName: swagger-ui-vanoord-service
            servicePort: 8080
          path: /

  tls:
  - hosts:
      {{- if .Values.prod}}
    - {{.Release.Namespace}}.{{.Values.ingress.proddomain}}
      {{- else }}
    - {{.Release.Namespace}}.{{.Values.ingress.devdomain}}
      {{- end}}
    secretName: swagger-ui-vanoord-ingress-secret
